version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    labels:
      - "dependabot"
    automerged_updates:
      enabled: true
      merge_type: "squash"
