site_name: My Docs

nav:
  - Home: index.md
  - DBT documentation: dtb_docs/index.html

docs_dir: 'docs/'

theme:
  name: 'material'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folder
